"use server"

import { revalidatePath } from "next/cache"
import { createClient, createAdminClient } from "@/lib/supabase/server"

/**
 * Ensures the current session belongs to an admin before any mutation.
 * Throws if not authenticated or not an admin.
 */
async function assertAdmin() {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) throw new Error("Not authenticated")

  const { data: profile } = await supabase
    .from("profiles")
    .select("role")
    .eq("id", user.id)
    .single()

  if (profile?.role !== "admin") throw new Error("Not authorized")
}

interface ManualOrderItemInput {
  product_id: string | null
  product_name: string
  product_sku: string | null
  product_image_url: string | null
  quantity: number
  unit_price: number
}

interface ManualOrderInput {
  // Customer: either an existing customer id, or new customer details
  customerId: string | null
  newCustomer: {
    name: string
    phone: string
    email: string
    address_line1: string
    address_line2: string
    city: string
    province: string
    postal_code: string
    notes: string
  } | null
  items: ManualOrderItemInput[]
  shippingCost: number
  discountAmount: number
  deliveryArea: string
  expectedDeliveryDate: string | null
  deliveryNotes: string
  shippingMethod: string // "delivery" | "pickup"
  orderNotes: string
  // Optional first payment captured at creation time
  initialPayment: {
    amount: number
    method: string
    reference: string
    paid_at: string
  } | null
}

export async function createManualOrder(input: ManualOrderInput) {
  await assertAdmin()
  const admin = createAdminClient()

  // 1. Resolve / create the customer record
  let customerId = input.customerId
  let customer: Record<string, any> | null = null

  if (!customerId && input.newCustomer) {
    const nc = input.newCustomer
    const { data: created, error: custErr } = await admin
      .from("customers")
      .insert({
        name: nc.name,
        phone: nc.phone || null,
        email: nc.email || null,
        address_line1: nc.address_line1 || null,
        address_line2: nc.address_line2 || null,
        city: nc.city || null,
        province: nc.province || null,
        postal_code: nc.postal_code || null,
        notes: nc.notes || null,
      })
      .select()
      .single()
    if (custErr) throw new Error(`Failed to create customer: ${custErr.message}`)
    customerId = created.id
    customer = created
  } else if (customerId) {
    const { data: existing } = await admin
      .from("customers")
      .select("*")
      .eq("id", customerId)
      .single()
    customer = existing
  }

  if (!customer) throw new Error("A customer is required")

  // 2. Compute totals
  const subtotal = input.items.reduce(
    (sum, it) => sum + it.unit_price * it.quantity,
    0,
  )
  const total = subtotal + (input.shippingCost || 0) - (input.discountAmount || 0)

  // 3. Split customer name for shipping fields
  const [firstName, ...rest] = (customer.name || "").trim().split(" ")
  const lastName = rest.join(" ")

  // 4. Create the order (order_number auto-generated by DB trigger)
  const { data: order, error: orderErr } = await admin
    .from("orders")
    .insert({
      source: "manual",
      customer_id: customerId,
      status: "processing",
      payment_status: "pending",
      payment_method: input.initialPayment?.method || "manual",
      subtotal,
      shipping_cost: input.shippingCost || 0,
      discount_amount: input.discountAmount || 0,
      total,
      shipping_method: input.shippingMethod === "pickup" ? "pickup" : "delivery",
      delivery_status: input.shippingMethod === "pickup" ? "collect" : "pending",
      delivery_area: input.deliveryArea || null,
      expected_delivery_date: input.expectedDeliveryDate || null,
      delivery_notes: input.deliveryNotes || null,
      notes: input.orderNotes || null,
      guest_email: customer.email || null,
      shipping_first_name: firstName || customer.name,
      shipping_last_name: lastName || null,
      shipping_address_line1: customer.address_line1 || null,
      shipping_address_line2: customer.address_line2 || null,
      shipping_city: customer.city || null,
      shipping_province: customer.province || null,
      shipping_postal_code: customer.postal_code || null,
      shipping_phone: customer.phone || null,
    })
    .select()
    .single()

  if (orderErr) throw new Error(`Failed to create order: ${orderErr.message}`)

  // 5. Look up cost prices for catalogue items so we can snapshot profit.
  const productIds = input.items
    .map((it) => it.product_id)
    .filter((id): id is string => Boolean(id))
  const costMap = new Map<string, number>()
  if (productIds.length > 0) {
    const { data: costRows } = await admin
      .from("products")
      .select("id, cost_price")
      .in("id", productIds)
    for (const row of costRows || []) {
      costMap.set(row.id, Number(row.cost_price) || 0)
    }
  }

  // Insert order items with a per-unit cost snapshot
  const itemsPayload = input.items.map((it) => ({
    order_id: order.id,
    product_id: it.product_id,
    product_name: it.product_name,
    product_sku: it.product_sku,
    product_image_url: it.product_image_url,
    quantity: it.quantity,
    unit_price: it.unit_price,
    unit_cost: it.product_id ? costMap.get(it.product_id) || 0 : 0,
    total_price: it.unit_price * it.quantity,
  }))

  const { error: itemsErr } = await admin.from("order_items").insert(itemsPayload)
  if (itemsErr) throw new Error(`Failed to add items: ${itemsErr.message}`)

  // 6. Optional initial payment (trigger recomputes payment_status)
  if (input.initialPayment && input.initialPayment.amount > 0) {
    const p = input.initialPayment
    const { error: payErr } = await admin.from("order_payments").insert({
      order_id: order.id,
      amount: p.amount,
      method: p.method || "cash",
      reference: p.reference || null,
      paid_at: p.paid_at,
    })
    if (payErr) throw new Error(`Failed to record payment: ${payErr.message}`)
  }

  revalidatePath("/admin/orders")
  revalidatePath("/admin/deliveries")
  return { orderId: order.id, orderNumber: order.order_number }
}

export async function addPayment(input: {
  orderId: string
  amount: number
  method: string
  reference: string
  paid_at: string
  notes: string
}) {
  await assertAdmin()
  const admin = createAdminClient()

  const { error } = await admin.from("order_payments").insert({
    order_id: input.orderId,
    amount: input.amount,
    method: input.method || "cash",
    reference: input.reference || null,
    paid_at: input.paid_at,
    notes: input.notes || null,
  })
  if (error) throw new Error(error.message)

  revalidatePath(`/admin/orders/${input.orderId}`)
  revalidatePath("/admin/orders")
}

export async function deletePayment(paymentId: string, orderId: string) {
  await assertAdmin()
  const admin = createAdminClient()

  const { error } = await admin.from("order_payments").delete().eq("id", paymentId)
  if (error) throw new Error(error.message)

  revalidatePath(`/admin/orders/${orderId}`)
  revalidatePath("/admin/orders")
}

export async function updateDelivery(input: {
  orderId: string
  delivery_status: string
  delivery_area: string
  expected_delivery_date: string | null
  delivery_notes: string
}) {
  await assertAdmin()
  const admin = createAdminClient()

  const patch: Record<string, any> = {
    delivery_status: input.delivery_status,
    delivery_area: input.delivery_area || null,
    expected_delivery_date: input.expected_delivery_date || null,
    delivery_notes: input.delivery_notes || null,
    updated_at: new Date().toISOString(),
  }
  // Stamp delivered_at when marked delivered; clear otherwise
  patch.delivered_at = input.delivery_status === "delivered" ? new Date().toISOString() : null

  const { error } = await admin.from("orders").update(patch).eq("id", input.orderId)
  if (error) throw new Error(error.message)

  revalidatePath(`/admin/orders/${input.orderId}`)
  revalidatePath("/admin/orders")
  revalidatePath("/admin/deliveries")
}

export async function upsertCustomer(input: {
  id?: string
  name: string
  phone: string
  email: string
  address_line1: string
  address_line2: string
  city: string
  province: string
  postal_code: string
  notes: string
}) {
  await assertAdmin()
  const admin = createAdminClient()

  const payload = {
    name: input.name,
    phone: input.phone || null,
    email: input.email || null,
    address_line1: input.address_line1 || null,
    address_line2: input.address_line2 || null,
    city: input.city || null,
    province: input.province || null,
    postal_code: input.postal_code || null,
    notes: input.notes || null,
  }

  if (input.id) {
    const { error } = await admin.from("customers").update(payload).eq("id", input.id)
    if (error) throw new Error(error.message)
  } else {
    const { error } = await admin.from("customers").insert(payload)
    if (error) throw new Error(error.message)
  }

  revalidatePath("/admin/customers/records")
}
