import { createClient, createAdminClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'

const lifestyleProducts = [
  {
    name: 'Ceramic Flat Plate (each)',
    slug: 'ceramic-flat-plate',
    description: 'Elegant black ceramic flat plate, perfect for everyday dining or special occasions. Durable and dishwasher safe.',
    short_description: 'Black ceramic flat plate for elegant dining',
    price: 28.00,
    sku: 'HL-PLATE-001',
    stock_quantity: 100,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/ceramic-flat-plate.jpg',
  },
  {
    name: 'Outdoor Shower (Rechargeable)',
    slug: 'outdoor-shower-rechargeable',
    description: 'Portable rechargeable outdoor shower with water container. Perfect for camping, beach trips, or garden use. Easy to use and convenient.',
    short_description: 'Portable rechargeable shower for outdoor use',
    price: 210.00,
    sku: 'HL-SHOWER-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/outdoor-shower.jpg',
  },
  {
    name: '3pcs Plastic Tray Set',
    slug: '3pcs-plastic-tray-set',
    description: 'Set of 3 elegant plastic serving trays with gold trim. Available in multiple colors. Perfect for serving snacks, drinks, or decorative display.',
    short_description: 'Elegant 3-piece serving tray set with gold trim',
    price: 240.00,
    sku: 'HL-TRAY-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/plastic-tray-set.jpg',
  },
  {
    name: '7L Ice Bucket with LED Light',
    slug: '7l-ice-bucket-led-light',
    description: '7 Liter ice bucket with color-changing LED lights. Perfect for parties and events. Creates a stunning visual effect while keeping drinks cold.',
    short_description: 'LED color-changing ice bucket for parties',
    price: 260.00,
    sku: 'HL-ICE-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/ice-bucket-led.jpg',
  },
  {
    name: '12pcs Silicon Spoon Set',
    slug: '12pcs-silicon-spoon-set',
    description: 'Complete set of 12 colorful silicone kitchen utensils. Heat resistant, non-stick friendly, and easy to clean. Includes various spoons and spatulas.',
    short_description: '12-piece colorful silicone kitchen utensil set',
    price: 200.00,
    sku: 'HL-SPOON-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/silicon-spoon-set.jpg',
  },
  {
    name: 'BreadBin Set',
    slug: 'breadbin-set',
    description: 'Stylish bread storage container set. Available in multiple colors including Cream, Matte Black, Matte Grey, and Navy Blue. Keeps bread fresh longer.',
    short_description: 'Stylish bread storage container in multiple colors',
    price: 450.00,
    sku: 'HL-BREAD-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/breadbin-set.jpg',
  },
  {
    name: '2pcs Coffee Table',
    slug: '2pcs-coffee-table',
    description: 'Elegant set of 2 round coffee tables with black marble-effect tops and gold metal legs. Perfect for modern living rooms. Nest together for space saving.',
    short_description: 'Set of 2 round coffee tables with gold legs',
    price: 650.00,
    sku: 'HL-TABLE-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/coffee-table-set.jpg',
  },
  {
    name: '4 Burner Gas Stove (Lightweight)',
    slug: '4-burner-gas-stove-lightweight',
    description: 'Portable 4 burner gas stove, lightweight design perfect for outdoor cooking, camping, or as a backup stove. Easy to transport and set up.',
    short_description: 'Portable lightweight 4 burner gas stove',
    price: 1690.00,
    sku: 'HL-STOVE-001',
    stock_quantity: 8,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/4-burner-gas-stove.jpg',
  },
  {
    name: 'Multifunctional Wet & Dry Vacuum',
    slug: 'multifunctional-wet-dry-vacuum',
    description: 'Powerful 12V motor wet and dry vacuum cleaner. Multifunctional design for home and car use. Includes multiple attachments for various cleaning tasks.',
    short_description: 'Powerful 12V wet & dry vacuum cleaner',
    price: 360.00,
    sku: 'HL-VAC-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/wet-dry-vacuum.jpg',
  },
  {
    name: 'Stanley Cup Tumbler',
    slug: 'stanley-cup-tumbler',
    description: 'Insulated tumbler cup with handle and straw. Keeps drinks cold for hours. Available in multiple colors including blue, green, purple, and pink.',
    short_description: 'Insulated tumbler cup with handle and straw',
    price: 160.00,
    sku: 'HL-CUP-001',
    stock_quantity: 50,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/stanley-cup.jpg',
  },
  {
    name: 'Throw Blanket',
    slug: 'throw-blanket',
    description: 'Soft and cozy throw blanket in various colorful patterns. Perfect for adding warmth and style to your living space. Machine washable.',
    short_description: 'Soft colorful throw blanket for home comfort',
    price: 190.00,
    sku: 'HL-BLANKET-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/throw-blanket.jpg',
  },
  {
    name: 'Eggs Holder',
    slug: 'eggs-holder',
    description: 'Stackable egg storage container in white/cream color. Keeps eggs organized and protected in your refrigerator. Space-saving design.',
    short_description: 'Stackable egg storage container',
    price: 110.00,
    sku: 'HL-EGG-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/eggs-holder.jpg',
  },
  {
    name: 'Soup Dish',
    slug: 'soup-dish',
    description: 'Elegant glass soup dish with gold metal frame and stand. Perfect for serving soups, salads, or as a decorative centerpiece. Luxurious design.',
    short_description: 'Elegant glass soup dish with gold frame',
    price: 355.00,
    sku: 'HL-SOUP-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/soup-dish.jpg',
  },
  {
    name: 'Sandals Adult',
    slug: 'sandals-adult',
    description: 'Comfortable adult slide sandals available in various colors. Perfect for indoor and outdoor use. Lightweight and easy to clean.',
    short_description: 'Comfortable adult slide sandals',
    price: 180.00,
    sku: 'HL-SANDAL-001',
    stock_quantity: 60,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/sandals-adult.jpg',
  },
  {
    name: '2pcs Travel Bags',
    slug: '2pcs-travel-bags',
    description: 'Set of 2 travel bags with wheels in purple/maroon color. Perfect for trips and vacations. Durable construction with smooth rolling wheels.',
    short_description: 'Travel luggage set with wheels',
    price: 395.00,
    sku: 'HL-TRAVEL-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/travel-bags.jpg',
  },
  {
    name: 'T60 Bag',
    slug: 't60-bag',
    description: 'Red sports and gym duffel bag with T60 branding. Spacious compartment for all your workout essentials. Durable and stylish design.',
    short_description: 'Red sports/gym duffel bag',
    price: 140.00,
    sku: 'HL-T60-001',
    stock_quantity: 35,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/t60-bag.jpg',
  },
  {
    name: '10pcs Pasta Bowls',
    slug: '10pcs-pasta-bowls',
    description: 'Set of 10 grey stackable pasta/soup bowls. Perfect for family dining. Durable construction and easy to store.',
    short_description: 'Set of 10 grey stackable pasta bowls',
    price: 290.00,
    sku: 'HL-PASTA-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/pasta-bowls.jpg',
  },
  {
    name: '5pcs Comforter Set',
    slug: '5pcs-comforter-set',
    description: '5-piece bedroom comforter set available in Mehroon and Light Grey colors. Includes comforter, sheets, and pillowcases. Soft and cozy for a good night\'s sleep.',
    short_description: '5-piece bedroom comforter set',
    price: 450.00,
    sku: 'HL-COMF-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/comforter-set.jpg',
  },
  {
    name: '3pcs Set Towels',
    slug: '3pcs-set-towels',
    description: 'Set of 3 white bath towels. Soft, absorbent, and durable. Perfect for bathroom or guest use.',
    short_description: 'Set of 3 white bath towels',
    price: 180.00,
    sku: 'HL-TOWEL-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/towel-set.jpg',
  },
  {
    name: '3pcs Stainless Steel Multifunction Food Warmer',
    slug: '3pcs-stainless-steel-food-warmer',
    description: 'Set of 3 stainless steel food warmers with lids. Perfect for buffets, parties, and keeping food warm. Elegant design for any occasion.',
    short_description: 'Set of 3 stainless steel food warmers',
    price: 595.00,
    sku: 'HL-WARM-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/food-warmer.jpg',
  },
  {
    name: 'Griller/Sandwich Maker',
    slug: 'griller-sandwich-maker',
    description: 'Electric sandwich maker and griller. Makes perfectly toasted sandwiches in minutes. Non-stick plates for easy cleaning.',
    short_description: 'Electric sandwich maker and griller',
    price: 285.00,
    sku: 'HL-GRILL-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/sandwich-maker.jpg',
  },
  {
    name: '6pcs Stainless Steel Knife Set',
    slug: '6pcs-stainless-steel-knife-set',
    description: '6-piece stainless steel kitchen knife set with wooden block. Includes chef knife, bread knife, utility knife, and more. Sharp and durable blades.',
    short_description: '6-piece stainless steel knife set with block',
    price: 330.00,
    sku: 'HL-KNIFE-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/knife-set.jpg',
  },
  {
    name: '3pcs Plastic Fruit Basket',
    slug: '3pcs-plastic-fruit-basket',
    description: 'Tiered 3-piece plastic fruit basket stand in brown/beige color. Perfect for displaying fruits on your kitchen counter. Space-saving vertical design.',
    short_description: 'Tiered 3-piece fruit basket stand',
    price: 320.00,
    sku: 'HL-FRUIT-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/fruit-basket.jpg',
  },
  {
    name: '2L Electric Glass Kettle',
    slug: '2l-electric-glass-kettle',
    description: '2 Liter electric glass kettle with blue LED light indicator. Fast boiling, auto shut-off, and boil-dry protection. Elegant design for modern kitchens.',
    short_description: '2L electric glass kettle with LED light',
    price: 275.00,
    sku: 'HL-KETTLE-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/electric-kettle.jpg',
  },
  {
    name: 'Bags 3 Collection',
    slug: 'bags-3-collection',
    description: 'Collection of 3 versatile bags in tan/brown and black colors. Includes backpack and travel bags. Perfect for everyday use, work, or travel.',
    short_description: 'Collection of 3 versatile bags',
    price: 250.00,
    sku: 'HL-BAG3-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/bags-collection.jpg',
  },
  {
    name: '3pcs Bakeware Set',
    slug: '3pcs-bakeware-set',
    description: 'Teal/turquoise 3-piece bakeware set including multiple baking trays and pans. Non-stick coating for easy food release and cleaning. Perfect for home baking.',
    short_description: 'Teal 3-piece non-stick bakeware set',
    price: 550.00,
    sku: 'HL-BAKE-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/bakeware-set.jpg',
  },
  {
    name: '4 Burner Gas Stove (Tabletop)',
    slug: '4-burner-gas-stove-tabletop',
    description: 'Compact 4 burner tabletop gas stove. Perfect for home kitchens or as an additional cooking surface. Durable construction with easy-to-clean surface.',
    short_description: 'Compact 4 burner tabletop gas stove',
    price: 550.00,
    sku: 'HL-STOVE-002',
    stock_quantity: 10,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/tabletop-gas-stove.jpg',
  },
  {
    name: '19pcs Silicon Kitchen Set',
    slug: '19pcs-silicon-kitchen-set',
    description: 'Complete 19-piece silicone kitchen utensil set in various colors including pink, mint, grey, and black. Heat resistant, non-stick friendly. Includes all essential cooking tools.',
    short_description: '19-piece silicone kitchen utensil set',
    price: 350.00,
    sku: 'HL-SIL19-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/silicon-kitchen-set-19.jpg',
  },
  {
    name: 'Modern Crocs (Size 6-10)',
    slug: 'modern-crocs-size-6-10',
    description: 'Modern style Crocs available in sizes 6 to 10. Comfortable, lightweight, and stylish. Perfect for casual wear, indoor or outdoor use.',
    short_description: 'Modern Crocs shoes sizes 6-10',
    price: 350.00,
    sku: 'HL-CROCS-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/modern-crocs.jpg',
  },
  {
    name: 'Modern 3pcs Food Warmer',
    slug: 'modern-3pcs-food-warmer',
    description: 'Elegant gold/amber colored 3-piece food warmer set with decorative glass pattern. Perfect for keeping food warm at dinner parties and special occasions.',
    short_description: 'Gold decorative 3-piece food warmer set',
    price: 595.00,
    sku: 'HL-MWARM-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/modern-food-warmer.jpg',
  },
  {
    name: '3pcs Character Kids Comforter',
    slug: '3pcs-character-kids-comforter',
    description: '3-piece kids comforter set featuring Lightning McQueen Cars characters. Includes comforter and pillowcases. Perfect for young car enthusiasts.',
    short_description: 'Lightning McQueen kids comforter set',
    price: 280.00,
    sku: 'HL-KIDSCOM-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/kids-comforter.jpg',
  },
  {
    name: 'Dinner Set',
    slug: 'dinner-set',
    description: 'Complete black/dark matte dinner set including plates, bowls, and cups. Modern minimalist design for elegant dining.',
    short_description: 'Black matte complete dinner set',
    price: 380.00,
    sku: 'HL-DINNER-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/dinner-set.jpg',
  },
  {
    name: 'Kitchen Knife Set (Case)',
    slug: 'kitchen-knife-set-case',
    description: 'Professional kitchen knife set in a convenient carrying case. Includes various knives and cutting tools. Perfect for home cooks and culinary enthusiasts.',
    short_description: 'Kitchen knife set in carrying case',
    price: 210.00,
    sku: 'HL-KNIFE-002',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/knife-set-case.jpg',
  },
  {
    name: '5pcs Food Warmer',
    slug: '5pcs-food-warmer',
    description: 'Set of 5 red/pink plastic food warmer containers with lids. Perfect for storing and reheating food. Microwave safe.',
    short_description: '5-piece plastic food warmer containers',
    price: 450.00,
    sku: 'HL-WARM5-001',
    stock_quantity: 18,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/food-warmer-5pcs.jpg',
  },
  {
    name: 'Winter Waterproof Warm Slippers',
    slug: 'winter-waterproof-warm-slippers',
    description: 'Cozy blue winter slippers with soft fur lining. Waterproof exterior keeps feet dry. Perfect for cold weather indoor comfort.',
    short_description: 'Blue winter slippers with fur lining',
    price: 120.00,
    sku: 'HL-SLIPPER-001',
    stock_quantity: 50,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/winter-slippers.jpg',
  },
  {
    name: '4 in 1 Rotating Vegetable Rack',
    slug: '4-in-1-rotating-vegetable-rack',
    description: 'Multi-tier rotating vegetable storage trolley in black. 4-in-1 design for organizing fruits, vegetables, and kitchen items. Space-saving rotating mechanism.',
    short_description: '4-tier rotating vegetable storage rack',
    price: 495.00,
    sku: 'HL-RACK-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/rotating-vegetable-rack.jpg',
  },
  {
    name: '10pcs Non-Stick Pots',
    slug: '10pcs-non-stick-pots',
    description: 'Premium 10-piece grey granite-style non-stick pot set with glass lids. Includes various sizes for all your cooking needs. Durable and easy to clean.',
    short_description: '10-piece granite non-stick pot set',
    price: 1720.00,
    sku: 'HL-POTS-001',
    stock_quantity: 8,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/non-stick-pots.jpg',
  },
  {
    name: '2 in 1 Cooler Box 20L',
    slug: '2-in-1-cooler-box-20l',
    description: 'TIMIN brand 2-in-1 cooler box set in blue and peach colors. 20L capacity keeps food and drinks cold for hours. Perfect for picnics, camping, and outdoor events.',
    short_description: '20L cooler box set in two colors',
    price: 995.00,
    sku: 'HL-COOLER-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/cooler-box.jpg',
  },
  {
    name: 'Dinner Set (White)',
    slug: 'dinner-set-white',
    description: 'Complete white dinner set including plates, bowls, and cups. Classic elegant design for everyday dining or special occasions.',
    short_description: 'White complete dinner set',
    price: 350.00,
    sku: 'HL-DINNER-002',
    stock_quantity: 18,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/dinner-set-white.jpg',
  },
  {
    name: '6L Pressure Cooker',
    slug: '6l-pressure-cooker',
    description: '6 Liter electric pressure cooker with digital display and multiple cooking modes. Fast, efficient, and safe cooking. Includes preset programs for various dishes.',
    short_description: '6L electric pressure cooker with digital display',
    price: 780.00,
    sku: 'HL-PRESSURE-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/pressure-cooker.jpg',
  },
  {
    name: '5pcs Plain Colour Bedspread',
    slug: '5pcs-plain-colour-bedspread',
    description: 'Elegant 5-piece plain colour bedspread set in beige/tan. Includes quilted bedspread and matching accessories. Soft and comfortable for a cozy bedroom.',
    short_description: 'Beige quilted 5-piece bedspread set',
    price: 390.00,
    sku: 'HL-BED-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/plain-bedspread.jpg',
  },
  {
    name: '8pcs Spice Jar Rotating Rack',
    slug: '8pcs-spice-jar-rotating-rack',
    description: 'Elegant 8-piece spice jar set on a rotating gold rack. Glass jars with gold lids for storing spices. Adds style and organization to your kitchen.',
    short_description: 'Rotating gold spice rack with 8 jars',
    price: 250.00,
    sku: 'HL-SPICE-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/spice-jar-rack.jpg',
  },
  {
    name: 'Quilted Weekender Travel Bag',
    slug: 'quilted-weekender-travel-bag',
    description: 'Stylish quilted weekender travel bag available in various colors. Spacious interior for weekend getaways. Durable construction with comfortable handles.',
    short_description: 'Quilted travel bag in various colors',
    price: 460.00,
    sku: 'HL-WEEKEND-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/quilted-weekender.jpg',
  },
  {
    name: 'Foldable Charcoal Grill',
    slug: 'foldable-charcoal-grill',
    description: 'Portable foldable charcoal BBQ grill. Easy to set up and fold for storage or transport. Perfect for outdoor cooking, camping, and braais.',
    short_description: 'Portable folding charcoal BBQ grill',
    price: 295.00,
    sku: 'HL-GRILL-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/foldable-grill.jpg',
  },
  {
    name: 'Steve Madden Bag',
    slug: 'steve-madden-bag',
    description: 'Stylish Steve Madden style black handbag. Elegant design perfect for work or casual outings. Spacious interior with multiple compartments.',
    short_description: 'Stylish black handbag',
    price: 350.00,
    sku: 'HL-SMADDEN-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/steve-madden-bag.jpg',
  },
  {
    name: 'Beautiful Cooler Box',
    slug: 'beautiful-cooler-box',
    description: 'Beautiful pastel-colored cooler boxes in pink, green, and peach. Keeps food and drinks cold for hours. Stylish design for picnics and outings.',
    short_description: 'Pastel colored cooler box',
    price: 695.00,
    sku: 'HL-BCOOLER-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/beautiful-cooler.jpg',
  },
  {
    name: 'Portable 20L Rice Container',
    slug: 'portable-20l-rice-container',
    description: 'Beige/cream portable 20L rice storage container with secure lid. Keeps rice fresh and protected from pests. Easy-pour spout for convenience.',
    short_description: '20L rice storage container with lid',
    price: 240.00,
    sku: 'HL-RICE-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/rice-container.jpg',
  },
  {
    name: 'Dish Rack',
    slug: 'dish-rack',
    description: 'Black metal 2-tier dish drying rack with drip tray. Organizes dishes, cups, and utensils. Space-saving design for kitchen counters.',
    short_description: '2-tier black metal dish drying rack',
    price: 320.00,
    sku: 'HL-DISH-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/dish-rack.jpg',
  },
  {
    name: '24pcs Stainless Steel Gold Cutlery',
    slug: '24pcs-stainless-steel-gold-cutlery',
    description: 'Elegant 24-piece gold stainless steel cutlery set in presentation box. Includes forks, knives, spoons, and teaspoons. Perfect for special occasions.',
    short_description: '24-piece gold cutlery set in box',
    price: 350.00,
    sku: 'HL-CUTLERY-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/gold-cutlery.jpg',
  },
  {
    name: '5pcs Fluffy Comforter',
    slug: '5pcs-fluffy-comforter',
    description: 'Luxurious 5-piece fluffy comforter set in mint/aqua color. Extra soft and plush for ultimate comfort. Includes comforter, sheets, and pillowcases.',
    short_description: 'Mint fluffy 5-piece comforter set',
    price: 550.00,
    sku: 'HL-FLUFFY-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/fluffy-comforter.jpg',
  },
  {
    name: 'Foldable Washing Basket',
    slug: 'foldable-washing-basket',
    description: 'Bamboo foldable laundry/washing basket. Eco-friendly and space-saving design. Collapses flat for easy storage when not in use.',
    short_description: 'Bamboo foldable laundry basket',
    price: 270.00,
    sku: 'HL-WASH-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/washing-basket.jpg',
  },
  {
    name: '6L Triple Cereal Dispenser',
    slug: '6l-triple-cereal-dispenser',
    description: 'Triple 6L cereal and dry food dispenser with black lids. Keeps cereals, grains, and snacks fresh. Wall-mounted or countertop design.',
    short_description: 'Triple cereal dispenser with black lids',
    price: 320.00,
    sku: 'HL-CEREAL-001',
    stock_quantity: 18,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/cereal-dispenser.jpg',
  },
  {
    name: 'Mini Structured Tote Bag',
    slug: 'mini-structured-tote-bag',
    description: 'Stylish mini structured tote bag available in yellow, white, and pink. Perfect for everyday use. Durable construction with elegant finish.',
    short_description: 'Mini structured tote in multiple colors',
    price: 350.00,
    sku: 'HL-TOTE-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/mini-tote-bag.jpg',
  },
  {
    name: 'Insulated Cooler Bag',
    slug: 'insulated-cooler-bag',
    description: 'Insulated cooler bag available in blue/yellow and olive/brown colors. Keeps food and drinks cold or hot. Perfect for picnics, lunch, and travel.',
    short_description: 'Insulated cooler bag for food & drinks',
    price: 120.00,
    sku: 'HL-ICOOL-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/insulated-cooler-bag.jpg',
  },
  {
    name: 'Combo Set (7pcs Cast Iron Pots + 12 Spoons)',
    slug: 'combo-set-cast-iron-pots-spoons',
    description: 'Complete combo set including 7 pieces cast iron pots in red and 12 kitchen spoons/utensils. Perfect starter set for new kitchens.',
    short_description: '7pcs cast iron pots + 12 utensils combo',
    price: 1670.00,
    sku: 'HL-COMBO-001',
    stock_quantity: 8,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/combo-set.jpg',
  },
  {
    name: '7pcs Food Storage Containers',
    slug: '7pcs-food-storage-containers',
    description: 'Set of 7 clear food storage containers with bamboo lids. Airtight seal keeps food fresh. Various sizes for different storage needs.',
    short_description: '7-piece food storage with bamboo lids',
    price: 310.00,
    sku: 'HL-STORAGE-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/food-storage.jpg',
  },
  {
    name: 'Easy Spin Cutter',
    slug: 'easy-spin-cutter',
    description: 'Green manual food chopper and spin cutter. Easy pull-cord operation for quick chopping of vegetables, fruits, and more. Compact and easy to clean.',
    short_description: 'Manual pull-cord food chopper',
    price: 60.00,
    sku: 'HL-SPIN-001',
    stock_quantity: 50,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/spin-cutter.jpg',
  },
  {
    name: 'Egg Shaped Cutlery Set',
    slug: 'egg-shaped-cutlery-set',
    description: 'Decorative egg-shaped cutlery holder with copper/rose gold top. Unique and elegant design for storing kitchen utensils. Makes a great centerpiece.',
    short_description: 'Decorative egg-shaped cutlery holder',
    price: 350.00,
    sku: 'HL-EGGCUT-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/egg-cutlery.jpg',
  },
  {
    name: '6pcs Bathroom Accessories',
    slug: '6pcs-bathroom-accessories',
    description: 'Complete 6-piece white bathroom accessory set. Includes soap dispenser, toothbrush holder, soap dish, and more. Modern minimalist design.',
    short_description: '6-piece white bathroom accessory set',
    price: 320.00,
    sku: 'HL-BATH-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/bathroom-accessories.jpg',
  },
  {
    name: '5pcs Corner Shower Caddy',
    slug: '5pcs-corner-shower-caddy',
    description: '5-piece black metal corner shower caddy/organizer with multiple tiers. Wall-mounted design for bathroom storage. Holds shampoo, soap, and toiletries.',
    short_description: 'Black metal corner shower organizer',
    price: 295.00,
    sku: 'HL-SHOWER-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/shower-caddy.jpg',
  },
  {
    name: 'Business Laptop Backpack',
    slug: 'business-laptop-backpack',
    description: 'Professional business laptop backpack available in black, burgundy, and olive colors. Multiple compartments for laptop, documents, and accessories.',
    short_description: 'Professional laptop backpack',
    price: 250.00,
    sku: 'HL-LAPTOP-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/laptop-backpack.jpg',
  },
  {
    name: 'Rechargeable Neck Fan',
    slug: 'rechargeable-neck-fan',
    description: 'Wearable rechargeable neck fan in white/teal color. 360-degree surrounding air flow. Hands-free cooling for outdoor activities and hot weather.',
    short_description: 'Wearable rechargeable neck fan',
    price: 130.00,
    sku: 'HL-FAN-001',
    stock_quantity: 35,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/neck-fan.jpg',
  },
  {
    name: 'Citrus Juicer',
    slug: 'citrus-juicer',
    description: 'Electric citrus juicer in mint/green color. Easy to use for fresh orange, lemon, and lime juice. Compact design for kitchen counter.',
    short_description: 'Electric citrus juicer in mint color',
    price: 190.00,
    sku: 'HL-JUICER-001',
    stock_quantity: 20,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/citrus-juicer.jpg',
  },
  {
    name: '5pcs Quilt (Different Colors)',
    slug: '5pcs-quilt-different-colors',
    description: '5-piece quilt bedding set available in different colors including teal/turquoise with floral design. Includes quilt and matching accessories for a complete bedroom makeover.',
    short_description: 'Colorful 5-piece quilt bedding set',
    price: 350.00,
    sku: 'HL-QUILT-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/quilt-set.jpg',
  },
  {
    name: '20L Food Storage Container',
    slug: '20l-food-storage-container',
    description: '20L food storage container/rice bucket in white. Airtight seal keeps food fresh and protected. Includes measuring cup and easy-pour spout.',
    short_description: '20L food storage rice bucket',
    price: 215.00,
    sku: 'HL-FOOD20-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/food-storage-20l.jpg',
  },
  {
    name: '10pcs Bon Voyager Pots',
    slug: '10pcs-bon-voyager-pots',
    description: '10-piece Bon Voyage Super stainless steel pot set with black handles and lids. South African quality brand, includes 5 pots in varying sizes.',
    short_description: '10-piece stainless steel pot set',
    price: 850.00,
    sku: 'HL-BONVOY-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/products/home-living/10pcs-bon-voyage-pots.jpg',
  },
  {
    name: 'Modern Knife Set with Stand',
    slug: 'modern-knife-set-with-stand',
    description: 'Modern knife set with wooden handles on rotating stand. Includes various knives for all kitchen tasks. Elegant design and sharp blades.',
    short_description: 'Modern knife set on rotating stand',
    price: 260.00,
    sku: 'HL-MKNIFE-001',
    stock_quantity: 18,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/modern-knife-set.jpg',
  },
  {
    name: 'Kitchen and Work Apron',
    slug: 'kitchen-and-work-apron',
    description: 'Black kitchen and work apron. Durable construction for cooking, grilling, and workshop use. Adjustable straps for comfortable fit.',
    short_description: 'Black kitchen/work apron',
    price: 95.00,
    sku: 'HL-APRON-001',
    stock_quantity: 40,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/kitchen-apron.jpg',
  },
  {
    name: '7pcs Cast Iron Pots',
    slug: '7pcs-cast-iron-pots',
    description: '7-piece blue cast iron pot set with various sizes. Includes pots, pans, and griddle. Superior heat retention for perfect cooking.',
    short_description: '7-piece blue cast iron pot set',
    price: 990.00,
    sku: 'HL-CAST-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/cast-iron-pots.jpg',
  },
  {
    name: '9kg New Empty Gas Cylinder (CADAC)',
    slug: '9kg-new-empty-gas-cylinder-cadac',
    description: 'New empty 9kg CADAC gas cylinder in blue. Ready for refilling at your local gas supplier. Durable and safe construction.',
    short_description: '9kg CADAC empty gas cylinder',
    price: 760.00,
    sku: 'HL-GAS-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/gas-cylinder.jpg',
  },
  {
    name: 'Hat/Spoty Bucket Hat',
    slug: 'hat-spoty-bucket-hat',
    description: 'Colorful bucket hats/sun hats available in various colors including orange, black, pink, and more. Perfect for outdoor activities and sun protection.',
    short_description: 'Colorful bucket sun hats',
    price: 80.00,
    sku: 'HL-HAT-001',
    stock_quantity: 60,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/bucket-hat.jpg',
  },
  {
    name: 'Car Fridge',
    slug: 'car-fridge',
    description: 'Portable car fridge/cooler in blue. Plugs into car cigarette lighter. Keeps food and drinks cold during travel and camping.',
    short_description: 'Portable car fridge cooler',
    price: 495.00,
    sku: 'HL-CARFRIDGE-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/car-fridge.jpg',
  },
  {
    name: 'Temperature Cup',
    slug: 'temperature-cup',
    description: 'Smart temperature display cup/mug in pink and green colors. Shows drink temperature on LED display. Perfect for tea and coffee lovers.',
    short_description: 'Temperature display smart cup',
    price: 140.00,
    sku: 'HL-TEMPCUP-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/temperature-cup.jpg',
  },
  {
    name: 'Foldable Table (also available in black)',
    slug: 'foldable-table',
    description: 'White foldable table with sturdy metal legs. Perfect for events, parties, camping, or extra dining space. Folds flat for easy storage. Also available in black.',
    short_description: 'White foldable table with metal legs',
    price: 650.00,
    sku: 'HL-TABLE-002',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/products/home-living/foldable-table.jpg',
  },
  {
    name: '7pcs DOLPHINE Cast Iron Pots',
    slug: '7pcs-dolphine-cast-iron-pots',
    description: '7-piece DOLPHINE brand orange cast iron pot set. Includes various pot sizes and pan. Superior heat retention for perfect cooking.',
    short_description: '7-piece orange cast iron pot set',
    price: 990.00,
    sku: 'HL-DOLPHINE-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/dolphine-cast-iron.jpg',
  },
  {
    name: 'FIELDBAR Cooler Box',
    slug: 'fieldbar-cooler-box',
    description: 'Premium FIELDBAR brand cooler box in grey. High-quality construction keeps contents cold for extended periods. Perfect for camping, fishing, and outdoor adventures.',
    short_description: 'Premium FIELDBAR cooler box',
    price: 1460.00,
    sku: 'HL-FIELDBAR-001',
    stock_quantity: 8,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/fieldbar-cooler.jpg',
  },
  {
    name: 'Foldable Bamboo Tray',
    slug: 'foldable-bamboo-tray',
    description: 'Elegant foldable bamboo breakfast tray with folding legs. Perfect for breakfast in bed or serving. Sturdy and lightweight.',
    short_description: 'Foldable bamboo breakfast tray',
    price: 210.00,
    sku: 'HL-BTRAY-001',
    stock_quantity: 25,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/bamboo-tray.jpg',
  },
  {
    name: '7pcs Dolphin Cast Iron Pots',
    slug: '7pcs-dolphin-cast-iron-pots',
    description: '7-piece orange enamel cast iron cookware set including 3 Dutch ovens with lids and 1 frying pan with cream interior',
    short_description: '7-piece orange cast iron pot set',
    price: 990.00,
    sku: 'HL-DOLPHIN7-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/products/home-living/7pcs-dolphin-cast-iron-pots.jpg',
  },
  {
    name: 'Wall Paper 3m',
    slug: 'wall-paper-3m',
    description: 'Decorative self-adhesive wallpaper in brown/marble pattern. 3 meters roll. Easy to apply and remove. Perfect for accent walls.',
    short_description: '3m decorative wallpaper roll',
    price: 240.00,
    sku: 'HL-WALLPAPER-001',
    stock_quantity: 30,
    is_active: true,
    is_featured: false,
    is_new: true,
    image_url: '/images/products/wallpaper.jpg',
  },
  {
    name: 'Combo 7pcs Cast Iron Pots with Utensils',
    slug: 'combo-7pcs-cast-iron-pots-utensils',
    description: 'Complete combo set with 7-piece red cast iron pots and matching kitchen utensils. Everything you need for cooking in one package.',
    short_description: 'Red cast iron pots + utensils combo',
    price: 1650.00,
    sku: 'HL-COMBO7-001',
    stock_quantity: 8,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/cast-iron-combo.jpg',
  },
  {
    name: '3 Tier Ceramic Serving Bowl',
    slug: '3-tier-ceramic-serving-bowl',
    description: 'Elegant 3-tier white/pink ceramic serving bowl on wooden stand. Perfect for serving fruits, snacks, or appetizers at parties and gatherings.',
    short_description: '3-tier ceramic serving bowl on stand',
    price: 845.00,
    sku: 'HL-3TIER-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/ceramic-serving-bowl.jpg',
  },
  {
    name: '8pcs Pots Set',
    slug: '8pcs-pots-set',
    description: '8-piece stainless steel pot set with glass lids. Various sizes for all cooking needs. Durable construction with heat-resistant handles.',
    short_description: '8-piece stainless steel pot set',
    price: 1050.00,
    sku: 'HL-8POTS-001',
    stock_quantity: 10,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/8pcs-pots.jpg',
  },
  {
    name: '7pcs Bedspread with Curtains',
    slug: '7pcs-bedspread-with-curtains',
    description: '7-piece bedspread set with matching curtains in green/teal color with decorative pattern. Complete bedroom makeover set.',
    short_description: 'Bedspread set with matching curtains',
    price: 495.00,
    sku: 'HL-BEDCURT-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/bedspread-curtains.jpg',
  },
  {
    name: '5pcs Reversible Comforter',
    slug: '5pcs-reversible-comforter',
    description: '5-piece reversible comforter set in blue with floral pattern. Can be flipped for a different look. Includes comforter, sheets, and pillowcases.',
    short_description: 'Blue reversible comforter set',
    price: 495.00,
    sku: 'HL-REVCOM-001',
    stock_quantity: 15,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/reversible-comforter.jpg',
  },
  {
    name: 'Gold Chaffing Dish',
    slug: 'gold-chaffing-dish',
    description: 'Elegant gold chafing dish with glass lid on gold stand. Perfect for keeping food warm at buffets, parties, and special events.',
    short_description: 'Gold chafing dish with glass lid',
    price: 520.00,
    sku: 'HL-CHAFF-001',
    stock_quantity: 12,
    is_active: true,
    is_featured: true,
    is_new: true,
    image_url: '/images/products/gold-chaffing-dish.jpg',
  },
]

export async function POST(request: Request) {
  try {
    // Allow seeding with secret key for development
    const url = new URL(request.url)
    const seedKey = url.searchParams.get('key')
    
    if (seedKey !== 'agrihub-seed-2024') {
      const supabase = await createClient()
      // Check if user is admin
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
      }
    }

    // Use admin client to bypass RLS
    const supabase = createAdminClient()

    // Get the Home & Living category ID
    const { data: category, error: categoryError } = await supabase
      .from('categories')
      .select('id')
      .eq('slug', 'home-living')
      .single()

    if (categoryError || !category) {
      return NextResponse.json({ error: 'Home & Living category not found' }, { status: 404 })
    }

    const results = {
      added: [] as string[],
      skipped: [] as string[],
      errors: [] as string[],
    }

    for (const product of lifestyleProducts) {
      // Check if product already exists
      const { data: existing } = await supabase
        .from('products')
        .select('id')
        .eq('slug', product.slug)
        .single()

      if (existing) {
        results.skipped.push(product.name)
        continue
      }

      // Insert the product
      const { error } = await supabase
        .from('products')
        .insert({
          ...product,
          category_id: category.id,
        })

      if (error) {
        results.errors.push(`${product.name}: ${error.message}`)
      } else {
        results.added.push(product.name)
      }
    }

    return NextResponse.json({
      success: true,
      message: `Added ${results.added.length} products, skipped ${results.skipped.length} existing products`,
      results,
    })
  } catch (error) {
    console.error('Error seeding lifestyle products:', error)
    return NextResponse.json({ error: 'Failed to seed products' }, { status: 500 })
  }
}
